name: Combined Test
on:
  push:
jobs:
  workflow-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dir
        run: |
          mkdir -p mydata/coffea mydata/rdf
         
      - name: Download Coffea-Base image
        run: docker pull coffeateam/coffea-base
        
      - name: Run Coffea-Base container
        run: docker run --rm -v $PWD:/code coffeateam/coffea-base bash -c 'cd code/analysis/coffea/ && python coffea_plot.py && mv *.png ../../mydata/coffea/ && mv PF_n.txt ../../mydata/coffea/ && ls'

      - name: Download ROOT-Base image
        run: docker pull rootproject/root

      - name: Run ROOT-Base container
        run: docker run --rm -v $PWD:/code rootproject/root bash -c 'cd ../code/analysis/coffea/ && python coffea_plot.py && mv *.png ../../mydata/rdf/ && ls'

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: Analysis Results
          path: mydata/
